export const categories = ["chair", "table", "sofa", "shelf", "desk"];

export const products = [
  {
    id: "1",
    isVisible: true,
    iconNames: ["1"],
    name: "Syltherine Cafe Chair",
    miniDescription: "A stylish and comfortable chair for cafes.",
    description: "A stylish and comfortable chair perfect for cafes.",
    currentPrice: 250,
    oldPrice: 357,
    categories: ["chair"],
    size: "85cm x 45cm x 45cm",
    material: "High-quality wood and cushioned seat",
    type: "Stylish",
    room: "Cafe",
    isOnSale: false,
  },
  {
    id: "2",
    isVisible: false,
    iconNames: ["2", "2", "5", "9"],
    name: "Leviosa Modern Dining Table",
    miniDescription: "A modern dining table perfect for contemporary homes.",
    description: "A sleek modern dining table ideal for contemporary homes.",
    currentPrice: 450,
    oldPrice: 599,
    categories: ["table"],
    size: "150cm x 90cm x 75cm",
    material: "Tempered glass top with metal legs",
    type: "Modern",
    room: "Dining Room",
    isOnSale: true,
  },
  {
    id: "3",
    isVisible: true,
    iconNames: ["3", "3", "8", "2"],
    name: "Nimbus Ergonomic Office Chair",
    miniDescription: "A comfortable and supportive office chair.",
    description:
      "A comfortable and supportive office chair for long work hours.",
    currentPrice: 300,
    oldPrice: 450,
    categories: ["chair"],
    size: "Adjustable height 90-110cm, seat width 50cm",
    material: "Mesh backrest with cushioned seat",
    type: "Ergonomic",
    room: "Office",
    isOnSale: true,
  },
  {
    id: "4",
    isVisible: true,
    iconNames: ["4", "4", "4", "4"],
    name: "Falcon Ergonomic Gaming Chair",
    miniDescription: "An ergonomic chair designed for gamers.",
    description:
      "An ergonomic gaming chair designed for ultimate comfort during long gaming sessions.",
    currentPrice: 400,
    oldPrice: 500,
    categories: ["chair"],
    size: "Adjustable height 120-140cm, seat width 55cm",
    material: "PU leather with memory foam padding",
    type: "Ergonomic",
    room: "Gaming Room",
    isOnSale: true,
  },
  {
    id: "5",
    isVisible: true,
    iconNames: ["5", "5", "7", "11"],
    name: "Phoenix Luxury Recliner",
    miniDescription: "A luxurious recliner for relaxation.",
    description: "A luxurious recliner perfect for ultimate relaxation.",
    currentPrice: 350,
    oldPrice: 470,
    categories: ["sofa"],
    size: "100cm x 90cm x 100cm",
    material: "Leather upholstery with high-density foam",
    type: "Luxury",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "6",
    isVisible: true,
    iconNames: ["6", "6", "6", "6"],
    name: "Griffin Modern Bar Stool",
    miniDescription: "A stylish bar stool for modern spaces.",
    description:
      "A stylish and contemporary bar stool ideal for modern spaces.",
    currentPrice: 150,
    oldPrice: 200,
    categories: ["chair"],
    size: "Adjustable height 60-80cm, seat diameter 35cm",
    material: "Metal frame with cushioned seat",
    type: "Modern",
    room: "Bar",
    isOnSale: true,
  },
  {
    id: "7",
    isVisible: true,
    iconNames: ["7", "7", "7", "7"],
    name: "Dragon Elegant Lounge Set",
    miniDescription: "An elegant lounge chair and sofa combo.",
    description: "An elegant lounge set featuring a chair and sofa combo.",
    currentPrice: 550,
    oldPrice: 650,
    categories: ["chair", "sofa"],
    size: "Chair: 80cm x 70cm x 85cm, Sofa: 200cm x 90cm x 85cm",
    material: "Velvet upholstery with wooden frame",
    type: "Elegant",
    room: "Lounge",
    isOnSale: true,
  },
  {
    id: "8",
    isVisible: true,
    iconNames: ["8", "8", "8", "8"],
    name: "Eagle Classic Wooden Chair",
    miniDescription: "A classic wooden chair with a timeless design.",
    description: "A classic wooden chair with a timeless design.",
    currentPrice: 120,
    oldPrice: 180,
    categories: ["chair"],
    size: "90cm x 45cm x 45cm",
    material: "Solid oak wood",
    type: "Classic",
    room: "Dining Room",
    isOnSale: true,
  },
  {
    id: "9",
    isVisible: true,
    iconNames: ["9", "9", "9", "9"],
    name: "Hawk Contemporary Accent Chair",
    miniDescription: "A contemporary accent chair for any room.",
    description: "A contemporary accent chair suitable for any room.",
    currentPrice: 320,
    oldPrice: 400,
    categories: ["chair"],
    size: "85cm x 75cm x 80cm",
    material: "Fabric upholstery with wooden legs",
    type: "Contemporary",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "10",
    isVisible: true,
    iconNames: ["10", "10", "10", "10"],
    name: "Raven Modern Swivel Chair",
    miniDescription: "A sleek swivel chair ideal for modern offices.",
    description: "A sleek swivel chair ideal for modern offices.",
    currentPrice: 220,
    oldPrice: 300,
    categories: ["chair"],
    size: "Adjustable height 85-100cm, seat width 50cm",
    material: "Mesh backrest with fabric seat",
    type: "Modern",
    room: "Office",
    isOnSale: true,
  },
  {
    id: "11",
    isVisible: true,
    iconNames: ["11", "11", "11", "11"],
    name: "Merlin Plush Armchair",
    miniDescription: "A plush armchair perfect for cozy corners.",
    description: "A plush armchair perfect for cozy corners.",
    currentPrice: 280,
    oldPrice: 350,
    categories: ["chair"],
    size: "90cm x 90cm x 90cm",
    material: "Soft fabric upholstery with foam padding",
    type: "Plush",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "12",
    isVisible: true,
    iconNames: ["1", "1", "1", "1"],
    name: "Goblin Minimalist Side Chair",
    miniDescription: "A minimalist side chair for additional seating.",
    description: "A minimalist side chair for additional seating.",
    currentPrice: 180,
    oldPrice: 230,
    categories: ["chair"],
    size: "85cm x 45cm x 45cm",
    material: "Metal frame with plastic seat",
    type: "Minimalist",
    room: "Living Room",
    isOnSale: false,
  },
  {
    id: "13",
    isVisible: true,
    iconNames: ["3", "3", "8", "2"],
    name: "Elf Versatile Folding Chair",
    miniDescription: "A versatile folding chair for easy storage.",
    description: "A versatile folding chair for easy storage and use.",
    currentPrice: 100,
    oldPrice: 150,
    categories: ["chair"],
    size: "85cm x 45cm x 45cm (unfolded), 85cm x 45cm x 10cm (folded)",
    material: "Metal frame with fabric seat",
    type: "Versatile",
    room: "Living Room",
    isOnSale: false,
  },
  {
    id: "14",
    isVisible: true,
    iconNames: ["4", "4", "4", "4"],
    name: "Centaur Adjustable Desk Chair",
    miniDescription: "An adjustable desk chair for ergonomic work.",
    description: "An adjustable desk chair for comfortable and ergonomic work.",
    currentPrice: 200,
    oldPrice: 275,
    categories: ["chair"],
    size: "Adjustable height 90-110cm, seat width 50cm",
    material: "Mesh backrest with cushioned seat",
    type: "Ergonomic",
    room: "Office",
    isOnSale: true,
  },
  {
    id: "15",
    isVisible: true,
    iconNames: ["5", "5", "7", "11"],
    name: "Gryphon Retro Lounge Set",
    miniDescription: "A retro-style lounge chair and sofa combination.",
    description: "A retro-style lounge chair and sofa combination.",
    currentPrice: 500,
    oldPrice: 600,
    categories: ["chair", "sofa"],
    size: "Chair: 80cm x 70cm x 85cm, Sofa: 200cm x 90cm x 85cm",
    material: "Fabric upholstery with wooden frame",
    type: "Retro",
    room: "Lounge",
    isOnSale: true,
  },
  {
    id: "16",
    isVisible: true,
    iconNames: ["6", "6", "6", "6"],
    name: "Pegasus Luxurious Wingback Chair",
    miniDescription: "A luxurious wingback chair for elegant spaces.",
    description:
      "A luxurious wingback chair for elegant and sophisticated spaces.",
    currentPrice: 600,
    oldPrice: 750,
    categories: ["chair"],
    size: "110cm x 75cm x 85cm",
    material: "Leather upholstery with wooden legs",
    type: "Luxurious",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "17",
    isVisible: true,
    iconNames: ["7", "7", "7", "7"],
    name: "Phoenix Classic Rocking Chair",
    miniDescription: "A classic rocking chair for relaxing moments.",
    description: "A classic rocking chair for relaxing moments.",
    currentPrice: 220,
    oldPrice: 290,
    categories: ["chair"],
    size: "100cm x 45cm x 90cm",
    material: "Wooden frame with cushioned seat",
    type: "Classic",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "18",
    isVisible: true,
    iconNames: ["8", "8", "8", "8"],
    name: "Hydra Contemporary Bean Bag Chair",
    miniDescription: "A contemporary bean bag chair for casual seating.",
    description:
      "A contemporary bean bag chair for casual and comfortable seating.",
    currentPrice: 130,
    oldPrice: 180,
    categories: ["chair"],
    size: "90cm x 90cm x 70cm",
    material: "Fabric cover with polystyrene bead filling",
    type: "Contemporary",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "19",
    isVisible: true,
    iconNames: ["9", "9", "9", "9"],
    name: "Unicorn Velvet Chaise Lounge",
    miniDescription: "A velvet chaise lounge for a touch of luxury.",
    description: "A luxurious velvet chaise lounge for elegant interiors.",
    currentPrice: 480,
    oldPrice: 600,
    categories: ["chair"],
    size: "150cm x 75cm x 85cm",
    material: "Velvet upholstery with wooden frame",
    type: "Luxury",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "20",
    isVisible: false,
    iconNames: ["2", "2", "5", "9"],
    name: "Phoenix Modern Sectional Sofa",
    miniDescription: "A modern sectional sofa for contemporary living rooms.",
    description:
      "A modern sectional sofa perfect for contemporary living rooms.",
    currentPrice: 900,
    oldPrice: 1200,
    categories: ["sofa"],
    size: "280cm x 90cm x 85cm",
    material: "Fabric upholstery with foam padding",
    type: "Modern",
    room: "Living Room",
    isOnSale: false,
  },
  {
    id: "21",
    isVisible: true,
    iconNames: ["3", "3", "8", "2"],
    name: "Minotaur Rustic Coffee Table",
    miniDescription: "A rustic coffee table for cozy living rooms.",
    description:
      "A rustic coffee table perfect for adding charm to cozy living rooms.",
    currentPrice: 350,
    oldPrice: 450,
    categories: ["table"],
    size: "120cm x 60cm x 45cm",
    material: "Reclaimed wood with metal frame",
    type: "Rustic",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "22",
    isVisible: true,
    iconNames: ["4", "4", "4", "4"],
    name: "Golem Industrial Bookshelf",
    miniDescription: "An industrial-style bookshelf for modern spaces.",
    description:
      "An industrial-style bookshelf that complements modern interiors.",
    currentPrice: 400,
    oldPrice: 550,
    categories: ["shelf"],
    size: "200cm x 100cm x 30cm",
    material: "Metal frame with wooden shelves",
    type: "Industrial",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "23",
    isVisible: true,
    iconNames: ["5", "5", "7", "11"],
    name: "Satyr Mid-Century Dining Chair",
    miniDescription:
      "A mid-century modern dining chair for elegant dining rooms.",
    description:
      "A mid-century modern dining chair for a touch of elegance in dining rooms.",
    currentPrice: 150,
    oldPrice: 200,
    categories: ["chair"],
    size: "85cm x 45cm x 45cm",
    material: "Wooden frame with cushioned seat",
    type: "Mid-Century",
    room: "Dining Room",
    isOnSale: true,
  },
  {
    id: "24",
    isVisible: false,
    iconNames: ["6", "6", "6", "6"],
    name: "Fairy Petite Vanity Table",
    miniDescription: "A petite vanity table perfect for compact spaces.",
    description: "A charming petite vanity table ideal for compact bedrooms.",
    currentPrice: 220,
    oldPrice: 300,
    categories: ["table"],
    size: "80cm x 40cm x 75cm",
    material: "Wood with mirror and drawers",
    type: "Petite",
    room: "Bedroom",
    isOnSale: false,
  },
  {
    id: "25",
    isVisible: true,
    iconNames: ["7", "7", "7", "7"],
    name: "Cyclops Outdoor Lounge Chair",
    miniDescription: "A durable lounge chair designed for outdoor relaxation.",
    description:
      "A durable and stylish lounge chair designed for outdoor relaxation.",
    currentPrice: 180,
    oldPrice: 250,
    categories: ["chair"],
    size: "85cm x 75cm x 90cm",
    material: "Weather-resistant rattan with cushioned seat",
    type: "Outdoor",
    room: "Patio",
    isOnSale: true,
  },
  {
    id: "26",
    isVisible: true,
    iconNames: ["8", "8", "8", "8"],
    name: "Centaur Modern Writing Desk",
    miniDescription: "A sleek writing desk perfect for modern home offices.",
    description:
      "A sleek and functional writing desk perfect for modern home offices.",
    currentPrice: 320,
    oldPrice: 400,
    categories: ["desk"],
    size: "120cm x 60cm x 75cm",
    material: "Wood with metal legs",
    type: "Modern",
    room: "Office",
    isOnSale: false,
  },
  {
    id: "27",
    isVisible: true,
    iconNames: ["9", "9", "9", "9"],
    name: "Phoenix Elegant Chaise Lounge",
    miniDescription: "An elegant chaise lounge for sophisticated spaces.",
    description:
      "An elegant chaise lounge that adds sophistication to any space.",
    currentPrice: 450,
    oldPrice: 600,
    categories: ["chair"],
    size: "160cm x 75cm x 80cm",
    material: "Velvet upholstery with wooden frame",
    type: "Elegant",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "28",
    isVisible: true,
    iconNames: ["2", "2", "5", "9"],
    name: "Ogre Minimalist TV Stand",
    miniDescription: "A minimalist TV stand ideal for modern living rooms.",
    description:
      "A minimalist TV stand designed to complement modern living rooms.",
    currentPrice: 300,
    oldPrice: 380,
    categories: ["stand"],
    size: "150cm x 45cm x 50cm",
    material: "Wood with metal frame",
    type: "Minimalist",
    room: "Living Room",
    isOnSale: true,
  },
  {
    id: "29",
    isVisible: true,
    iconNames: ["3", "3", "8", "2"],
    name: "Griffin Luxury King Bed",
    miniDescription: "A luxurious king-size bed for a restful sleep.",
    description:
      "A luxurious king-size bed designed for a restful and comfortable sleep.",
    currentPrice: 800,
    oldPrice: 1000,
    categories: ["bed"],
    size: "200cm x 180cm x 100cm",
    material: "Wood frame with upholstered headboard",
    type: "Luxury",
    room: "Bedroom",
    isOnSale: false,
  },
  {
    id: "30",
    isVisible: true,
    iconNames: ["5", "5", "7", "11"],
    name: "Sphinx Modern Shoe Rack",
    miniDescription: "A modern shoe rack for organized entryways.",
    description:
      "A modern and functional shoe rack for organized and tidy entryways.",
    currentPrice: 100,
    oldPrice: 150,
    categories: ["rack"],
    size: "90cm x 30cm x 90cm",
    material: "Metal frame with wooden shelves",
    type: "Modern",
    room: "Entryway",
    isOnSale: true,
  },
];
